<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="lidar_length" value="0.06" />
    <xacro:property name="lidar_radius" value="0.025" />
    <xacro:property name="lidar_hov" value="80 * ${pi / 180.0}" />


    <link name="lidar_link">
        <visual>
            <origin xyz="0 0 -${lidar_length/2.0}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
            <material name="grey" />
        </visual>
    </link>

    <joint name="base_lidar_joint" type="fixed">
        <parent link="base_link" />
        <child link="lidar_link" />
        <origin xyz="0 0 ${base_height+lidar_length}" rpy="0 0 0" />
    </joint>

    <gazebo reference="lidar_link">
        <sensor name='gpu_lidar' type='gpu_lidar'>
            <topic>scan</topic>
            <update_rate>10</update_rate>
            <always_on>true</always_on>
            <visualize>true</visualize>
            <gz_frame_id>lidar_link</gz_frame_id>
            <pose relative_to='lidar_link'>0 0 0 0 0 0</pose>
            <ray>
                <scan>
                    <horizontal>
                        <samples>640</samples>
                        <resolution>1</resolution>
                        <min_angle>-${lidar_hov}</min_angle>
                        <max_angle>${lidar_hov}</max_angle>
                    </horizontal>
                    <vertical>
                        <samples>1</samples>
                        <resolution>0.01</resolution>
                        <min_angle>0</min_angle>
                        <max_angle>0</max_angle>
                    </vertical>
                </scan>
                <range>
                    <min>0.08</min>
                    <max>10.0</max>
                    <resolution>0.01</resolution>
                </range>
            </ray>
        </sensor>
    </gazebo>

</robot>